export enum MailType {
  RESET = "RESET",
  CREATE = "CREATE",
  RECOVERY_EMAIL_SETUP = "RECOVERY_EMAIL_SETUP",
  EMAIL_RECOVERY = "EMAIL_RECOVERY",
  NEWSLETTER_SUBSCRIPTION = 'NEWSLETTER_SUBSCRIPTION' 
}
